### ISSUE TITLE
Dual DC-17S

### ISSUE THREAD

**Issue by Defterscroll** [Outer-Rim-Armory/Aux-Mod#265]
## Environment
Arma version: `x.xx`
ACE version `x.xx`

## Describe the bug
When switching to said weapon stuns will be loaded and chosen instead of starting with lethal firemode

## To reproduce
1. Go to arsenal and load the weapon with stun on person

## Expected behavior
Expected it to be on lethal when swapped leading to dangerous situations

## Attachments
If applicable, add screenshots to help explain your problem. **At the bare minimum, include an RPT (log) file.**

**Comment by DartRuffian** [comment]
I just tried in-game and it will just be on whatever fire-mode you left the gun on last time.
If you changed to stuns, swapped to your primary, and swapped back, it will still be on stun. The same applies for the normal fire mode.

**Comment by DartRuffian** [comment]
@Defterscroll As far as I can tell, you are describing expected behavior of Arma. Are you wanting the dual DC-17s (or any sidearm) to *always* default to a lethal mode when swapped to?

**Comment by Defterscroll** [comment]
@DartRuffian Yes that is what I would want.

**Comment by DartRuffian** [comment]
In that case, this is not a bug and I'm not going to change the vanilla behavior of keeping the last mode/muzzle that was selected.
