### ISSUE TITLE
Issue with standalone jetpacks mod

### ISSUE THREAD

**Issue by CmdrGree** [Outer-Rim-Armory/Aux-Mod#267]
## Feature
Option to disable certain features when configuring jetpacks.
1. Automatic freefall prevention - currently set to only be active when jetpack script is in use, works great - however, it breaks freefall prevention zones, and disables itself when the jetpack is not in use. I've had real issues using this at extremally high altitude in a space-themed mission I made, and when using the combination of jetpack scripts I use for my unit atm (slightly cursed, I know).
2. Teleporting 30m behind vehicles when dismounting - this has consistently been really disruptive to my group when we're using ground based vehicles and with landed air-based vehicles.
3. ~~Refuelling not working - I'll make a standalone bug report about this at a later date.~~

## Is your feature request related to a problem?
Yes

## Describe your solution or changes
1. Option in jetpack config to disable freefall prevention feature. i.e. a `freefall_prevention = false;` variable in the jetpack config.
2. Option in addon options to disable vehicle dismount teleport.
3. ~~I just fixed this on my end by setting the fuel drain coefficient to 0%~~

## Possible alternatives
1. Alternative to my solution to 1 would be to have freefall prevention always on while the jetpack is worn, not just while in use, or alternatively have an option in addon options to turn off the freefall prevention part of the script.

## Additional context
All of my issues are relating to the Keeli Company - Standalone Jetpacks mod. I do not use the aux mod.

**Comment by DartRuffian** [comment]
> Automatic freefall prevention - currently set to only be active when jetpack script is in use, works great - however, it breaks freefall prevention zones, and disables itself when the jetpack is not in use. I've had real issues using this at extremally high altitude in a space-themed mission I made, and when using the combination of jetpack scripts I use for my unit atm (slightly cursed, I know).
Freefall height is only changed if the jetpack has a `BNA_KC_jetpacks_freefallHeight` value higher than 0, and then always reset when a player is no longer using a jetpack. Mods like freefall fix shouldn't be affected by it since the height is always updated on each frame, but things could be adjusted.

> Teleporting 30m behind vehicles when dismounting - this has consistently been really disruptive to my group when we're using ground based vehicles and with landed air-based vehicles.
This should only ever trigger if a vehicle is *not* touching the ground or is less than 10 meters off the ground, but a setting could be added for it easily.

> All of my issues are relating to the Keeli Company - Standalone Jetpacks mod. I do not use the aux mod.
They're the same system, the standalone just only has the required parts of the aux (i.e. `main`, `jetpacks`, and `particles`

**Comment by CmdrGree** [comment]
The issue with the fall prevention is the reset that happens when the jetpack is not in use, if there was an option to disable that reset, that'd be great. As it stands, I am unable to use the jetpack mod in my missions because it keeps resetting the freefall height.

**Comment by DartRuffian** [comment]
Then yeah just manually setting it would cause an issue, every group I've seen has just used a mod like Freefall Fix to prevent issues like that. I can throw in some extra logic to reset the player's freefall height to what it was set to before, rather than the engine default

**Comment by DartRuffian** [comment]
> Refuelling not working - I'll make a standalone bug report about this at a later date.
As for this, what "isn't working"?
The refueling from bodies has always been a bit weird, but should be working. And there's also a placeable prop for refueling your jetpack to full anyway.

**Comment by CmdrGree** [comment]
> Then yeah just manually setting it would cause an issue, every group I've seen has just used a mod like Freefall Fix to prevent issues like that. I can throw in some extra logic to reset the player's freefall height to what it was set to before, rather than the engine default

That would be greatly appreciated!

> As for this, what "isn't working"?
When I make an object a refuelling station, the interaction does not refuel the jetpack and then the interaction is gone. Also, the interaction wasn't appearing at all in multiplayer.

As I said, I'll make a proper bug report for that once I've gone back and got all the specifics, it's the only actual bug I've had - the others are features I had issues with. Just setting the fuel consumption to 0% works for my group's purposes, so it's not really time critical and I'll produce a proper bug report at a later date with more accurate details. :)

**Comment by DartRuffian** [comment]
> > Then yeah just manually setting it would cause an issue, every group I've seen has just used a mod like Freefall Fix to prevent issues like that. I can throw in some extra logic to reset the player's freefall height to what it was set to before, rather than the engine default
> 
> That would be greatly appreciated!

It will take the larger of the config height and the player's current height, and then always reset to the player's original height when landing:
```sqf
// fnc_jetpackStart.sqf
if (_freefallHeight > 0) then {
    private _originalHeight = (getUnitFreefallInfo ace_player) select 2;
    ace_player setVariable [QGVAR(freefallHeight), _originalHeight];
    ace_player setUnitFreefallHeight (_freefallHeight max _originalHeight);
};
```

```sqf
// fnc_jetpackPFH.sqf - _exitCode
private _originalHeight = _unit getVariable [QGVAR(freefallHeight), -1];
_unit setUnitFreefallHeight _originalHeight;
```

**Comment by CmdrGree** [comment]
> It will take the larger of the config height and the player's current height, and then always reset to the player's original height when landing

That should do the trick! Much appreciated! I'll let ya know if we have any issues. :)

**Comment by DartRuffian** [comment]
> When I make an object a refuelling station, the interaction does not refuel the jetpack and then the interaction is gone. Also, the interaction wasn't appearing at all in multiplayer.

The action is hidden if your jetpack is full. If you can provide a video of it happening with that later bug report that would be appreciated.
