### ISSUE TITLE
Add Deactivate Jetpack keybind

### ISSUE THREAD

**Issue by CmdrGree** [Outer-Rim-Armory/Aux-Mod#269]
## Is your feature request related to a problem?
When falling with the jetpack on, we are limited to ~10m/s or so max fall speed even without slow-fall.

## Describe your solution or changes
A key to turn off the jetpack mid-flight.

## Possible alternatives
An option to turn off the fall speed limit in mission settings.

## Additional context
Request from one of my unit members.
> so keeli jetpack makes it so you cannot fall faster than ~10m/s, thats just with it on, not the slow fall which makes it ~5m/s, so you'll still take damage on a fall, but youll likely be shot out of the sky before you can get to the ground to take fall damage. so definitely dont recommend using the keeli pack if you plan on fast inserts. would be nice to remove the speed limit, though ideally, we could shut the jetpack off mid air like the 3as jetpack, because reduced fall speed is a nice feature, but not if you cant turn it off. really would only mean it needs a separate keybind for on and up instead of being the same and only turning off on the ground.

**Comment by DartRuffian** [comment]
It's not really intended to be activated, for example, as soon as you jump out of a vehicle since making a bunch of noise and being a giant light in the sky would make you an obvious target anyway.

But yes, a keybind could made very easily

**Comment by DartRuffian** [comment]
@CmdrGree I can't think of a fitting default keybind, so it will simply be unbound by default.

**Comment by CmdrGree** [comment]
Ori'vor'e! Many thanks! My unit members are very pleased!
