### ISSUE TITLE
Get out of water hotkey or feature.

### ISSUE THREAD

**Issue by CmdrGree** [Outer-Rim-Armory/Aux-Mod#271]
## Is your feature request related to a problem?
No

## Describe your solution or changes
I have been messing around with jetpacking around a map that has water on it. However, whenever I land in water I am unable to get out of it without swimming to the water's edge. It would be fantastic to have a feature for when you are at the water's surface to jetpack out of the water into the air.

## Possible alternatives
Perhaps a prevention measure that stops us from going into water while the jetpack is active? I guess that would be a low height limit or something?

## Additional context
In season 2 and 3 of the Mandalorian, various Mandalorians use a jetpack to jump out of the water. [Here's the clip from season 2 on youtube](https://www.youtube.com/clip/UgkxqigSelv4POaAOHPcJwbLLFsFuGbnuqWB?si=E6Q82oIVgZLLDAv1). I can provide the clip from season 3 if you want, but it is a spoiler.

**Comment by DartRuffian** [comment]
It's mainly an animation issue, and setVelocity being weird in water

**Comment by CmdrGree** [comment]
Yow, I've made most of the script for jumping out of the water. I don't know what the keybind ID is for your jump key, but I figure you can sort that out on your end.

Here's the code:

```sqf
if (animationState player find 'sdv' != -1 || animationState player find 'ssw' != -1) then 
{
player switchMove "stand";
_currentPos = getPosASLW player;
player setPosASLW [_currentPos #0, _currentPos #1, -0.9];
_newVelocity = velocity player vectorAdd [0,0,10];
player setVelocity _newVelocity;
}
```

I currently have this set up as an action that I put on the player (I can provide the full code if you need it), but it should really have a custom keybind and be hooked into your mod directly. I figure using the same keybind as the "activate jetpack" keybind would be best.

The if statement checks if the player is in a "surface dive" or "surface swim" animation.

The code then set the player to stand and moves them up slightly so they are out of the water, then sets their velocity to +10 upwards along with preserving whatever their underwater velocity was.

Hope this helps!

**Comment by CmdrGree** [comment]
Here's a video of the action I made being used.
[![Video of testing my action](https://img.youtube.com/vi/PMR_nGPrths/hqdefault.jpg)](https://www.youtube.com/embed/PMR_nGPrths)

```sqf
this addAction [
"Water Boost",
{
params ["_target", "_caller", "_actionId", "_arguments"];
_caller playMoveNow "stand";
_currentPos = getPosASLW _caller;
_caller setPosASLW [_currentPos #0, _currentPos #1, -0.9];
_newVelocity = velocity _caller vectorAdd [0,0,10];
_caller setVelocity _newVelocity;
},
nil,
7,
false,
false,
"User1",
"(animationState _originalTarget find 'sdv' != -1 || animationState _originalTarget find 'ssw' != -1)"
];
```
Here's the full code for the action if you want to test it. It's currently set to use the "User1" keybind by default, so set that to whatever you want. Just place this in the unit's init field in 3DEN.

**Comment by DartRuffian** [comment]
Interesting, so it doesn't look like `setVelocity` has an issue with water like I thought, unless that had changed since I originally done my testing for jetpacks.

In that case yeah, I'll totally add some logic for being able to jump out of the water.

**Comment by CmdrGree** [comment]
nono, your original statement is correct, setVelocity does have an issue with water, that's why I had to use the setPosition to move out of the water before setting velocity. :)

**Comment by DartRuffian** [comment]
That's just how setVelocity works with units, you need a small teleport to make them airborne otherwise their velocity changes but they don't move.

**Comment by CmdrGree** [comment]
Gotcha!

**Comment by CmdrGree** [comment]
Yow! Using your feedback, I managed to get a deep jump feature working. Here's the code:

```sqf
this addAction [
"Water Boost",
{
params ["_target", "_caller", "_actionId", "_arguments"];
_caller spawn {
_currentPos = getPosASLW _this;
_this setPosASLW _currentPos;
while {getPosASLW _this #2 <= 0} do {
_this playMoveNow "stand";
_newVelocity = velocity _this vectorAdd [0,0,10];
_this setVelocity _newVelocity;
sleep 0.2
};
};
},
nil,
7,
false,
false,
"User1",
"(animationState _originalTarget find 'sdv' != -1 || animationState _originalTarget find 'ssw' != -1 || animationState _originalTarget find 'swm' != -1 || animationState _originalTarget find 'dve' != -1 || animationState _originalTarget find 'bsw' != -1 || animationState _originalTarget find 'bdv' != -1)"
];
```

I expanded the list of possible animations you can be in to go up. 

This action now lets you go up at any point in the water column. If you implement this I highly recommend having a separate hotkey for it. 

The lower down in the water you are, the higher the resulting jump will be. You can adjust this by changing the sleep timer within the spawn I think.

**Comment by CmdrGree** [comment]
In my testing I've also found a small bug where if you go close to the water's surface, you can't go up or down very fast at all.
https://youtu.be/6BIVyBJv8F4

During my brief testing of my script, I did manage to get stuck and hurt at the bottom of the water from my boost script
https://youtu.be/d-VjDVYDksg

**Comment by DartRuffian** [comment]
Yeah I found some cases where you'd rise super slow for some reason, couldn't figure out why. None of them were major issues though so I opted to leave them as-is.

**Comment by CmdrGree** [comment]
I'll let you know how it goes with my clan members.

Reckon you'll implement the deep water boost, or shall I test that alongside the regular script as an addAction for now?

**Comment by DartRuffian** [comment]
There's a setting for the max depth you can jump from

**Comment by CmdrGree** [comment]
Aye, but that just teleports you to the surface. The code I posted more recently is for this action that works without needing to teleport any distance. Here's the video example ttps://youtu.be/d-VjDVYDksg

**Comment by DartRuffian** [comment]
If it's teleporting you to the surface than I forgot to change the height
